### ISSUE TITLE
Error when running multiple prediction file submissions

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#12]
```
WARNING: The SHARE_RESULTS_IMMEDIATELY variable is not set. Defaulting to a blank string.
WARNING: The DATA_UNLOCK_SYNAPSE_PRINCIPAL_ID variable is not set. Defaulting to a blank string.
Pulling workflow-hook (sagebionetworks/synapseworkflowhook:)...
latest: Pulling from sagebionetworks/synapseworkflowhook
516433960039: Pull complete
083ed1d8baf8: Pull complete
973ddf6ced71: Pull complete
febb8320d7db: Pull complete
affad3486051: Pull complete
9702fa0409b0: Pull complete
bd219431247b: Pull complete
840183798047: Pull complete
bf9ee603b199: Pull complete
df4c8b841faa: Pull complete
ed692ecd08d0: Pull complete
e66c107068d5: Pull complete
bb4a82c98007: Pull complete
5c5f031a5721: Pull complete
b427c3c4ae9c: Pull complete
Digest: sha256:87037d978d225e33a4639660e879c46e36adcee9ee4b5338b626f4c4c937e10b
Status: Downloaded newer image for sagebionetworks/synapseworkflowhook:latest
Creating synapseworkflowhook_workflow-hook_1 ... done
Attaching to synapseworkflowhook_workflow-hook_1
workflow-hook_1  | [INFO] Scanning for projects...
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom
Downloaded from central: http://repo1.maven.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom (7.7 kB at 14 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/28/mojo-parent-28.pom
Downloaded from central: http://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/28/mojo-parent-28.pom (26 kB at 84 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/codehaus/codehaus-parent/3/codehaus-parent-3.pom
Downloaded from central: http://repo1.maven.org/maven2/org/codehaus/codehaus-parent/3/codehaus-parent-3.pom (4.1 kB at 24 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.jar
Downloaded from central: http://repo1.maven.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.jar (38 kB at 97 kB/s)
workflow-hook_1  | [INFO] 
workflow-hook_1  | [INFO] ------------------< org.sagebionetworks:WorkflowHook >------------------
workflow-hook_1  | [INFO] Building WorkflowHook 1.0-SNAPSHOT
workflow-hook_1  | [INFO] --------------------------------[ jar ]---------------------------------
workflow-hook_1  | [INFO] 
workflow-hook_1  | [INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ WorkflowHook >>>
workflow-hook_1  | [INFO] 
workflow-hook_1  | [INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ WorkflowHook <<<
workflow-hook_1  | [INFO] 
workflow-hook_1  | [INFO] 
workflow-hook_1  | [INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ WorkflowHook ---
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom
Downloaded from central: http://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom (601 B at 3.5 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/apache/maven/maven/2.0/maven-2.0.pom
Downloaded from central: http://repo1.maven.org/maven2/org/apache/maven/maven/2.0/maven-2.0.pom (8.8 kB at 46 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.pom
Downloaded from central: http://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.pom (11 kB at 59 kB/s)
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar
workflow-hook_1  | Downloading from central: http://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
Downloaded from central: http://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar (53 kB at 75 kB/s)
Downloaded from central: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar (195 kB at 237 kB/s)
workflow-hook_1  | ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - Precheck completed successfully.
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - Top level loop: checking progress or starting new job.
workflow-hook_1  | 23:46:03.158 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:46:03 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:46:04.472 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:46:04 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn16809914
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - Mounting: /var/run
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - workingDir: /Users/ThomasY/sandbox/04a4f6c8-b7b5-47c0-8fcc-cce7a2531070
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - toil cmd: [toil-cwl-runner, --defaultMemory, 100M, --retryCount, 0, --defaultDisk, 1000000, --workDir, /Users/ThomasY/sandbox/04a4f6c8-b7b5-47c0-8fcc-cce7a2531070, --noLinkImports, ChallengeWorkflowTemplates-master/scoringHarness_workflow.cwl, /Users/ThomasY/sandbox/04a4f6c8-b7b5-47c0-8fcc-cce7a2531070/TMP13827562428750995613.yaml]
workflow-hook_1  | 23:51:53.436 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:51:53 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:51:54.074 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:51:54 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn16809914
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - Mounting: /var/run
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - workingDir: /Users/ThomasY/sandbox/964c869e-5b60-43e7-8755-bf75e4912978
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - toil cmd: [toil-cwl-runner, --defaultMemory, 100M, --retryCount, 0, --defaultDisk, 1000000, --workDir, /Users/ThomasY/sandbox/964c869e-5b60-43e7-8755-bf75e4912978, --noLinkImports, ChallengeWorkflowTemplates-master/scoringHarness_workflow.cwl, /Users/ThomasY/sandbox/964c869e-5b60-43e7-8755-bf75e4912978/TMP10522415605006310025.yaml]
workflow-hook_1  | 23:51:58.406 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:51:58 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:51:59.084 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:51:59 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn16809914
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - Mounting: /var/run
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - workingDir: /Users/ThomasY/sandbox/412e8180-c7a2-4ecb-91cf-29e3639275f0
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - toil cmd: [toil-cwl-runner, --defaultMemory, 100M, --retryCount, 0, --defaultDisk, 1000000, --workDir, /Users/ThomasY/sandbox/412e8180-c7a2-4ecb-91cf-29e3639275f0, --noLinkImports, ChallengeWorkflowTemplates-master/scoringHarness_workflow.cwl, /Users/ThomasY/sandbox/412e8180-c7a2-4ecb-91cf-29e3639275f0/TMP130819673196750346.yaml]
workflow-hook_1  | 23:52:02.979 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:02 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:52:05.402 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:05 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn16809914
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - Mounting: /var/run
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - workingDir: /Users/ThomasY/sandbox/82b9a94b-b764-495b-932d-df02eb802875
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WES - toil cmd: [toil-cwl-runner, --defaultMemory, 100M, --retryCount, 0, --defaultDisk, 1000000, --workDir, /Users/ThomasY/sandbox/82b9a94b-b764-495b-932d-df02eb802875, --noLinkImports, ChallengeWorkflowTemplates-master/scoringHarness_workflow.cwl, /Users/ThomasY/sandbox/82b9a94b-b764-495b-932d-df02eb802875/TMP12633298927877995977.yaml]
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Found 4860 bytes to log.
workflow-hook_1  | 23:52:13.275 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:13 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:52:14.516 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:14 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681440 already exists with a parentId: syn16809938
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Will archive /tmp/9681440_logs.txt
workflow-hook_1  | 23:52:17.544 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:17 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681440_logs.zip already exists with a parentId: syn16810000
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Archived /tmp/9681440_logs.txt to syn16810001
workflow-hook_1  | Oct 02, 2018 11:52:19 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Will not retry: Submission Status: 9681440 was updated since you last fetched it, retrieve it again and reapply the update
workflow-hook_1  | 23:52:19.629 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:19 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | WARNING: Encountered exception on attempt 0: Submission Status: 9681440 was updated since you last fetched it, retrieve it again and reapply the update
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - Top level loop: checking progress or starting new job.
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Found 5114 bytes to log.
workflow-hook_1  | 23:52:31.534 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:31 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:52:32.779 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:32 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681563 already exists with a parentId: syn16809938
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Will archive /tmp/9681563_logs.txt
workflow-hook_1  | 23:52:36.961 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:36 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681563_logs.zip already exists with a parentId: syn16924996
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Archived /tmp/9681563_logs.txt to syn16924997
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Found 5114 bytes to log.
workflow-hook_1  | 23:52:41.321 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:41 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn16809914
workflow-hook_1  | 23:52:42.248 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:42 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681565 already exists with a parentId: syn16809938
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Will archive /tmp/9681565_logs.txt
workflow-hook_1  | 23:52:44.507 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Oct 02, 2018 11:52:44 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9681565_logs.zip already exists with a parentId: syn16925040
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Archived /tmp/9681565_logs.txt to syn16925041
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.WorkflowHook - Pipeline failed
workflow-hook_1  | com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: sha256:16205494406aa6822de54a8de1784e932429843a79e7a0dc63affdad048f1fde"}
workflow-hook_1  | 
workflow-hook_1  | 	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
workflow-hook_1  | 	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
workflow-hook_1  | 	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
workflow-hook_1  | 	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
workflow-hook_1  | 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
workflow-hook_1  | 	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
workflow-hook_1  | 	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
workflow-hook_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
workflow-hook_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
workflow-hook_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
workflow-hook_1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
workflow-hook_1  | 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
workflow-hook_1  | 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
workflow-hook_1  | 	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
workflow-hook_1  | 	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
workflow-hook_1  | 	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
workflow-hook_1  | 	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
workflow-hook_1  | 	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
workflow-hook_1  | 	at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:64)
workflow-hook_1  | 	at org.sagebionetworks.DockerUtils.removeImage(DockerUtils.java:407)
workflow-hook_1  | 	at org.sagebionetworks.WES.deleteWorkFlowJob(WES.java:327)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.updateJob(WorkflowHook.java:500)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.updateWorkflowJobs(WorkflowHook.java:342)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.execute(WorkflowHook.java:185)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.main(WorkflowHook.java:103)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
workflow-hook_1  | 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
workflow-hook_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)
workflow-hook_1  | [WARNING] 
workflow-hook_1  | java.lang.reflect.InvocationTargetException
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
workflow-hook_1  |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  |     at java.lang.reflect.Method.invoke (Method.java:566)
workflow-hook_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
workflow-hook_1  |     at java.lang.Thread.run (Thread.java:834)
workflow-hook_1  | Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: sha256:16205494406aa6822de54a8de1784e932429843a79e7a0dc63affdad048f1fde"}
workflow-hook_1  | 
workflow-hook_1  |     at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter (ResponseStatusExceptionFilter.java:47)
workflow-hook_1  |     at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply (ClientFilteringStages.java:140)
workflow-hook_1  |     at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply (ClientFilteringStages.java:128)
workflow-hook_1  |     at org.glassfish.jersey.process.internal.Stages.process (Stages.java:171)
workflow-hook_1  |     at org.glassfish.jersey.client.ClientRuntime.invoke (ClientRuntime.java:257)
workflow-hook_1  |     at org.glassfish.jersey.client.JerseyInvocation$1.call (JerseyInvocation.java:684)
workflow-hook_1  |     at org.glassfish.jersey.client.JerseyInvocation$1.call (JerseyInvocation.java:681)
workflow-hook_1  |     at org.glassfish.jersey.internal.Errors.process (Errors.java:315)
workflow-hook_1  |     at org.glassfish.jersey.internal.Errors.process (Errors.java:297)
workflow-hook_1  |     at org.glassfish.jersey.internal.Errors.process (Errors.java:228)
workflow-hook_1  |     at org.glassfish.jersey.process.internal.RequestScope.runInScope (RequestScope.java:444)
workflow-hook_1  |     at org.glassfish.jersey.client.JerseyInvocation.invoke (JerseyInvocation.java:681)
workflow-hook_1  |     at org.glassfish.jersey.client.JerseyInvocation$Builder.method (JerseyInvocation.java:411)
workflow-hook_1  |     at org.glassfish.jersey.client.JerseyInvocation$Builder.delete (JerseyInvocation.java:360)
workflow-hook_1  |     at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute (RemoveImageCmdExec.java:27)
workflow-hook_1  |     at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute (RemoveImageCmdExec.java:11)
workflow-hook_1  |     at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec (AbstrSyncDockerCmdExec.java:23)
workflow-hook_1  |     at com.github.dockerjava.core.command.AbstrDockerCmd.exec (AbstrDockerCmd.java:35)
workflow-hook_1  |     at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec (RemoveImageCmdImpl.java:64)
workflow-hook_1  |     at org.sagebionetworks.DockerUtils.removeImage (DockerUtils.java:407)
workflow-hook_1  |     at org.sagebionetworks.WES.deleteWorkFlowJob (WES.java:327)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.updateJob (WorkflowHook.java:500)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.updateWorkflowJobs (WorkflowHook.java:342)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.execute (WorkflowHook.java:185)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.main (WorkflowHook.java:103)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
workflow-hook_1  |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  |     at java.lang.reflect.Method.invoke (Method.java:566)
workflow-hook_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
workflow-hook_1  |     at java.lang.Thread.run (Thread.java:834)
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [INFO] BUILD FAILURE
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [INFO] Total time: 06:53 min
workflow-hook_1  | [INFO] Finished at: 2018-10-02T23:52:47Z
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project WorkflowHook: An exception occured while executing the Java class. null: InvocationTargetException: {"message":"No such image: sha256:16205494406aa6822de54a8de1784e932429843a79e7a0dc63affdad048f1fde"} -> [Help 1]
workflow-hook_1  | [ERROR] 
workflow-hook_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
workflow-hook_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
workflow-hook_1  | [ERROR] 
workflow-hook_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
workflow-hook_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
workflow-hook_1  | [Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down signal received.
workflow-hook_1  | [Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down complete.
synapseworkflowhook_workflow-hook_1 exited with code 1
```

**Comment by thomasyu888** [comment]
I observe one submission that is "ACCEPTED" and the rest is stuck at "EVALUATION_IN_PROGRESS".  I observed this one time, so I cleared all my docker images and docker containers and tried again.  

Still the same result.  

Not sure what is going on

**Comment by brucehoff** [comment]
I added a try/catch around removal of a container or image so that an error isn't propagated if the container/image is not found.  If you find that images are accumulating and not getting cleaned up, more investigation will be needed.

**Comment by thomasyu888** [comment]
Perfect. Thanks so much for your help. Can you explain what container is removed here? Does it have an impact on if the rest of the submissions are ran to completion.

**Comment by brucehoff** [comment]
> Can you explain what container is removed here? 

That's a good question.  The workflow hook starts a new container running the Toil workflow engine for each submission.  When the submission is done the hook removes the container and the image.

... and this may explain the problem: we shouldn't be deleting the image, just the container, since the  same image is used for all jobs.   I just updated the 'hook not to delete a submission's image, just its container.  

By the way, if a workflow creates its own containers it is responsible for cleaning them up when its done (deleting the container and image).

**Comment by thomasyu888** [comment]
Does this mean we need to have a "remove image and container" step in the workflow?

**Comment by brucehoff** [comment]
> Does this mean we need to have a "remove image and container" step in the workflow?

It might be best to do this as the tail-end of the workflow step that runs the container since, in the long term, different steps might run on different machines and the clean up must run on the same machine that ran the container.  So you might incorporate the clean up into this .cwl:

https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/runDocker.cwl
