### ISSUE TITLE
Get github repo error

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#36]
```
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9683999 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684000 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684001 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684120 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684121 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684122 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684123 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684124 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684125 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684126 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684127 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684128 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684129 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684130 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684131 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684132 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684133 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684134 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684135 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684136 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684137 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684138 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684139 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684140 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684141 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684142 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684143 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684144 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684145 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684146 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684147 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684148 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684149 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684150 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684151 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684152 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684153 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684154 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684155 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684156 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684157 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684158 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684159 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684160 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684161 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684162 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684163 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684164 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684166 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684167 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684168 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684169 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684170 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684171 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684172 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684173 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684174 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684175 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684195 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684197 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684198 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684199 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684200 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684201 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684202 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - We have met or exceeded the maximum concurrent workflow count, 4, so we will not start 9684203 at this time.
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - PROGRESS: null
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Found 18443 bytes to log.
00:53:52.813 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 12:53:52 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn17055973
00:53:53.385 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 12:53:53 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9683849 already exists with a parentId: syn17056009
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Will archive /tmp/9683849_logs.txt
00:53:55.044 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 12:53:55 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9683849_logs.zip already exists with a parentId: syn17090298
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.Archiver - Archived /tmp/9683849_logs.txt to syn17090310
[org.sagebionetworks.WorkflowHook.main()] INFO org.sagebionetworks.WorkflowHook - Top level loop: checking progress or starting new job.
[org.sagebionetworks.WorkflowHook.main()] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://repo-prod.prod.sagebase.org:443: The target server failed to respond
[org.sagebionetworks.WorkflowHook.main()] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {s}->https://repo-prod.prod.sagebase.org:443
01:04:19.335 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 1:04:19 AM org.sagebionetworks.ExponentialBackoffRunner execute
WARNING: Encountered exception on attempt 0: Failed to perform request.
01:04:26.025 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 1:04:26 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230 already exists with a parentId: syn17055973
01:04:26.848 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 1:04:26 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9683850 already exists with a parentId: syn17056007
01:04:27.064 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 1:04:27 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3324230_LOCKED already exists with a parentId: syn17055973
01:04:27.662 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Jan 04, 2019 1:04:27 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 9683850 already exists with a parentId: syn17056009
[org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.WorkflowHook - Submission failed
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at java.base/java.net.URL.openStream(URL.java:1117)
	at org.sagebionetworks.WES.downloadZip(WES.java:80)
	at org.sagebionetworks.WES.downloadWorkflowFromURL(WES.java:104)
	at org.sagebionetworks.WES.createWorkflowJob(WES.java:167)
	at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs(WorkflowHook.java:248)
	at org.sagebionetworks.WorkflowHook.execute(WorkflowHook.java:186)
	at org.sagebionetworks.WorkflowHook.main(WorkflowHook.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	... 20 more
[WARNING] 
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
    at sun.security.ssl.SSLSocketImpl.handleEOF (SSLSocketImpl.java:1321)
    at sun.security.ssl.SSLSocketImpl.decode (SSLSocketImpl.java:1160)
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord (SSLSocketImpl.java:1063)
    at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:402)
    at sun.net.www.protocol.https.HttpsClient.afterConnect (HttpsClient.java:567)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect (AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1581)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1509)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:245)
    at java.net.URL.openStream (URL.java:1117)
    at org.sagebionetworks.WES.downloadZip (WES.java:80)
    at org.sagebionetworks.WES.downloadWorkflowFromURL (WES.java:104)
    at org.sagebionetworks.WES.createWorkflowJob (WES.java:167)
    at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs (WorkflowHook.java:248)
    at org.sagebionetworks.WorkflowHook.execute (WorkflowHook.java:186)
    at org.sagebionetworks.WorkflowHook.main (WorkflowHook.java:105)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.SSLSocketInputRecord.decode (SSLSocketInputRecord.java:167)
    at sun.security.ssl.SSLTransport.decode (SSLTransport.java:108)
    at sun.security.ssl.SSLSocketImpl.decode (SSLSocketImpl.java:1152)
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord (SSLSocketImpl.java:1063)
    at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:402)
    at sun.net.www.protocol.https.HttpsClient.afterConnect (HttpsClient.java:567)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect (AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1581)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1509)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:245)
    at java.net.URL.openStream (URL.java:1117)
    at org.sagebionetworks.WES.downloadZip (WES.java:80)
    at org.sagebionetworks.WES.downloadWorkflowFromURL (WES.java:104)
    at org.sagebionetworks.WES.createWorkflowJob (WES.java:167)
    at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs (WorkflowHook.java:248)
    at org.sagebionetworks.WorkflowHook.execute (WorkflowHook.java:186)
    at org.sagebionetworks.WorkflowHook.main (WorkflowHook.java:105)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:834)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:44 h
[INFO] Finished at: 2019-01-04T01:21:39Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project WorkflowHook: An exception occured while executing the Java class. null: InvocationTargetException: Remote host terminated the handshake: SSL peer shut down incorrectly -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down signal received.
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down complete.
```

**Comment by thomasyu888** [comment]
All containers have exited

**Comment by thomasyu888** [comment]
After discussion with @brucehoff, he came to the conclusion that this is a `github` issue.  Should add exponential backoff to getting the github repo

**Comment by brucehoff** [comment]
Just needed a little exponential back-off/retry.
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/90ff5906322ac3e00df7082be06b50983b948c68
