### ISSUE TITLE
Submission Status update fail

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#37]
```Workflow Administrator:

Submission 9684291 failed.  The workflow description is: WorkflowJobImpl [submissionId=null, containerName=workflow_job.6dd08500-f813-4559-87c7-699c29a6b364, container=com.github.dockerjava.api.model.Container@fbb82a5[command=toil-cwl-runner --defaultMemory 100M --retryCount 0 --defaultDisk 1000000 --workDir /home/ec2-user/workflow/69c0d89d-0114-4617-b6a6-5a8145367f5e --noLinkImports NCI-CPTAC-Challenge-workflowtest/workflow/docker_agent_workflow.cwl /home/ec2-user/workflow/69c0d89d-0114-4617-b6a6-5a8145367f5e/TMP7245377986362766294.yaml,created=1546917980,id=7b31bda2d55a637f48d9adc789bdc8520cb9cc55e8f2b8169e6c9510b48b1411,image=sagebionetworks/synapseworkflowhook-toil,imageId=sha256:c4703064a385f3a1f1605ad5bc186b8c54da5ca502ee22b0df0ad99bf32ccbb6,names={/workflow_job.6dd08500-f813-4559-87c7-699c29a6b364},ports={},labels={},status=Up About an hour,sizeRw=,sizeRootFs=,hostConfig=com.github.dockerjava.api.model.ContainerHostConfig@6afcae48[networkMode=default],networkSettings=com.github.dockerjava.api.model.ContainerNetworkSettings@732b386c[networks={bridge=com.github.dockerjava.api.model.ContainerNetwork@1899ac59[ipamConfig=,links=,aliases=,networkID=abc7698dfad1511313b2444dd225d5192569002844abb54752ee8db278e0df17,endpointId=a6e57d6b67130d6f96c3cb42559589af1d67b3a36253b4fb54ca6a363a149992,gateway=172.17.0.1,ipAddress=172.17.0.2,ipPrefixLen=16,ipV6Gateway=,globalIPv6Address=,globalIPv6PrefixLen=0,macAddress=02:42:ac:11:00:02]}]], submissionParameters=null]


 The message is:

	org.sagebionetworks.client.exceptions.SynapseConflictingUpdateException: Submission Status: 9684291 was updated since you last fetched it, retrieve it again and reapply the update
	at org.sagebionetworks.client.ClientUtils.throwException(ClientUtils.java:79)
	at org.sagebionetworks.client.ClientUtils.throwException(ClientUtils.java:159)
	at org.sagebionetworks.client.ClientUtils.convertResponseBodyToJSONAndThrowException(ClientUtils.java:108)
	at org.sagebionetworks.client.BaseClientImpl.putJson(BaseClientImpl.java:452)
	at org.sagebionetworks.client.BaseClientImpl.putJSONEntity(BaseClientImpl.java:561)
	at org.sagebionetworks.client.SynapseClientImpl.updateSubmissionStatus(SynapseClientImpl.java:2999)
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy27.updateSubmissionStatus(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:46)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:43)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:64)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:43)
	at com.sun.proxy.$Proxy27.updateSubmissionStatus(Unknown Source)
	at org.sagebionetworks.SubmissionUtils$1.execute(SubmissionUtils.java:90)
	at org.sagebionetworks.SubmissionUtils$1.execute(SubmissionUtils.java:87)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:64)
	at org.sagebionetworks.SubmissionUtils.updateSubmissionStatus(SubmissionUtils.java:87)
	at org.sagebionetworks.WorkflowHook.updateWorkflowJobs(WorkflowHook.java:417)
	at org.sagebionetworks.WorkflowHook.execute(WorkflowHook.java:187)
	at org.sagebionetworks.WorkflowHook.main(WorkflowHook.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by brucehoff** [comment]
Added more debug info to help sleuth this problem: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/9609ef30c65627d76f4c9f3fa0bf2c6069d18fac

**Comment by brucehoff** [comment]
No activity in 1/2 year.  Please reopen if more is needed.
