### ISSUE TITLE
Add COMPOSE_PROJECT_NAME to the readme, or else error...

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/SynapseWorkflowHook#48]
I just restarted my instance that was running the hook. I cleared all my docker images and containers. After starting up the hook, whenever I make a submission to the queue I get this error:

workflow-hook_1  | Aug 09, 2019 5:56:09 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3360851 already exists with a parentId: syn20078502
workflow-hook_1  | 17:56:10.287 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
workflow-hook_1  | Aug 09, 2019 5:56:10 PM org.sagebionetworks.ExponentialBackoffRunner execute
workflow-hook_1  | SEVERE: Found status code 409. Will not retry: Status Code: 409 message: An entity with the name: 3360851_LOCKED already exists with a parentId: syn20078502
workflow-hook_1  | [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.WorkflowHook - Submission failed
workflow-hook_1  | java.lang.RuntimeException: Cannot find value for COMPOSE_PROJECT_NAME
workflow-hook_1  | 	at org.sagebionetworks.Utils.getProperty(Utils.java:116)
workflow-hook_1  | 	at org.sagebionetworks.Utils.getProperty(Utils.java:87)
workflow-hook_1  | 	at org.sagebionetworks.Utils.dockerComposeName(Utils.java:77)
workflow-hook_1  | 	at org.sagebionetworks.WES.createDirInHostMountedSharedDir(WES.java:74)
workflow-hook_1  | 	at org.sagebionetworks.WES.createWorkflowJob(WES.java:177)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs(WorkflowHook.java:263)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.execute(WorkflowHook.java:201)
workflow-hook_1  | 	at org.sagebionetworks.WorkflowHook.main(WorkflowHook.java:111)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
workflow-hook_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
workflow-hook_1  | 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
workflow-hook_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)
workflow-hook_1  | [WARNING] 
workflow-hook_1  | java.lang.reflect.InvocationTargetException
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
workflow-hook_1  |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  |     at java.lang.reflect.Method.invoke (Method.java:566)
workflow-hook_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
workflow-hook_1  |     at java.lang.Thread.run (Thread.java:834)
workflow-hook_1  | Caused by: java.lang.RuntimeException: Cannot find value for COMPOSE_PROJECT_NAME
workflow-hook_1  |     at org.sagebionetworks.Utils.getProperty (Utils.java:116)
workflow-hook_1  |     at org.sagebionetworks.Utils.getProperty (Utils.java:87)
workflow-hook_1  |     at org.sagebionetworks.Utils.dockerComposeName (Utils.java:77)
workflow-hook_1  |     at org.sagebionetworks.WES.createDirInHostMountedSharedDir (WES.java:74)
workflow-hook_1  |     at org.sagebionetworks.WES.createWorkflowJob (WES.java:177)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs (WorkflowHook.java:263)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.execute (WorkflowHook.java:201)
workflow-hook_1  |     at org.sagebionetworks.WorkflowHook.main (WorkflowHook.java:111)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
workflow-hook_1  |     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
workflow-hook_1  |     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
workflow-hook_1  |     at java.lang.reflect.Method.invoke (Method.java:566)
workflow-hook_1  |     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
workflow-hook_1  |     at java.lang.Thread.run (Thread.java:834)
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [INFO] BUILD FAILURE
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [INFO] Total time:  01:00 min
workflow-hook_1  | [INFO] Finished at: 2019-08-09T17:56:13Z
workflow-hook_1  | [INFO] ------------------------------------------------------------------------
workflow-hook_1  | [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project WorkflowHook: An exception occured while executing the Java class. null: InvocationTargetException: Cannot find value for COMPOSE_PROJECT_NAME -> [Help 1]
workflow-hook_1  | [ERROR] 
workflow-hook_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
workflow-hook_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
workflow-hook_1  | [ERROR] 
workflow-hook_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
workflow-hook_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
workflow-hook_1  | [Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down signal received.
workflow-hook_1  | [Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down complete.
compose.cli.verbose_proxy.proxy_callable: docker wait <- (u'140d45eb68c80b30f76a6efa59f3af5491cc27cd334359812770d095a4106557')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'140d45eb68c80b30f76a6efa59f3af5491cc27cd334359812770d095a4106557')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/140d45eb68c80b30f76a6efa59f3af5491cc27cd334359812770d095a4106557/wait HTTP/1.1" 200 30
compose.cli.verbose_proxy.proxy_callable: docker wait -> 1
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/140d45eb68c80b30f76a6efa59f3af5491cc27cd334359812770d095a4106557/json HTTP/1.1" 200 None
synapseworkflowhook_workflow-hook_1 exited with code 1
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'/bin/sh',
           u'-c',
           u'exec mvn exec:java -DentryPoint=org.sagebionetworks.WorkflowHook'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
...

**Comment by thomasyu888** [comment]
Need to add to `.env`: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/blob/master/.envTemplate#L7

**Comment by andrewelamb** [comment]
I added the above field and now getting:

workflow-hook_1  | [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project WorkflowHook: An exception occured while executing the Java class. null: InvocationTargetException: {"message":"get workflow_orchestrator_shared: no such volume"} -> [Help 1]

**Comment by andrewelamb** [comment]
I added RUN_WORKFLOW_CONTAINER_IN_PRIVILEGED_MODE=true
and got the same error

**Comment by andrewelamb** [comment]
This was fixed by:
COMPOSE_PROJECT_NAME=workfloworchestrator
instead of this:
COMPOSE_PROJECT_NAME=workflow_orchestrator
in my .env file
I noticed this volume:
workfloworchestrator_shared
was being created
