### ISSUE TITLE
Invalid session token error

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#50]
```- Top level loop: checking progress or starting new job.
23:57:24.216 [org.sagebionetworks.WorkflowHook.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Oct 08, 2019 11:57:24 PM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: Invalid session token
[WARNING] 
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:834)
Caused by: org.sagebionetworks.client.exceptions.SynapseUnauthorizedException: Invalid session token
    at org.sagebionetworks.client.ClientUtils.throwException (ClientUtils.java:69)
    at org.sagebionetworks.client.ClientUtils.throwException (ClientUtils.java:159)
    at org.sagebionetworks.client.ClientUtils.convertResponseBodyToJSONAndThrowException (ClientUtils.java:108)
    at org.sagebionetworks.client.BaseClientImpl.getJson (BaseClientImpl.java:417)
    at org.sagebionetworks.client.BaseClientImpl.getPaginatedResults (BaseClientImpl.java:669)
    at org.sagebionetworks.client.SynapseClientImpl.getAllSubmissionBundlesByStatus (SynapseClientImpl.java:3088)
    at jdk.internal.reflect.GeneratedMethodAccessor23.invoke (Unknown Source)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke (SynapseProfileProxy.java:55)
    at com.sun.proxy.$Proxy27.getAllSubmissionBundlesByStatus (Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor23.invoke (Unknown Source)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.sagebionetworks.SynapseClientFactory$1$1.execute (SynapseClientFactory.java:46)
    at org.sagebionetworks.SynapseClientFactory$1$1.execute (SynapseClientFactory.java:43)
    at org.sagebionetworks.ExponentialBackoffRunner.execute (ExponentialBackoffRunner.java:64)
    at org.sagebionetworks.SynapseClientFactory$1.invoke (SynapseClientFactory.java:43)
    at com.sun.proxy.$Proxy27.getAllSubmissionBundlesByStatus (Unknown Source)
    at org.sagebionetworks.EvaluationUtils.selectSubmissions (EvaluationUtils.java:384)
    at org.sagebionetworks.WorkflowHook.createNewWorkflowJobs (WorkflowHook.java:230)
    at org.sagebionetworks.WorkflowHook.execute (WorkflowHook.java:205)
    at org.sagebionetworks.WorkflowHook.main (WorkflowHook.java:112)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:834)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23:49 h
[INFO] Finished at: 2019-10-08T23:57:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project WorkflowHook: An exception occured while executing the Java class. null: InvocationTargetException: Invalid session token -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down signal received.
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down complete.```

**Comment by thomasyu888** [comment]
I believe this will impact any challenge that is using this infrastructure (Hook or Orchestrator).  Current workaround is to restart the hook, but theres no notification when the hook stops.  Our collaborators continuously inform us that submissions aren't being run.

**Comment by vpchung** [comment]
Came across this error with the Allen Institute challenge as well.

**Comment by thomasyu888** [comment]
RA2 challenge as well (using the orchestrator jar file)

**Comment by brucehoff** [comment]
The fix is to continuously (ea. 10 sec) log in. This ensures that the session token is valid.   Here's the change in the Orchestrator:
https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/commit/af5eb7bab592af7371941e913b32f05976164238

**Comment by thomasyu888** [comment]
Awesome. Thank you!

**Comment by thomasyu888** [comment]
Hmm. I seem to be getting this error with the jar executable:
```
[thomas.yu@sagebionetworks.org@login001 ~]$ java -jar WorkflowOrchestrator-1.0-SNAPSHOT-jar-with-dependencies.jar 
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[main] INFO org.sagebionetworks.WorkflowOrchestrator - Precheck completed successfully.
14:00:20.638 [main] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Oct 30, 2019 2:00:20 PM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: Anonymous users have only READ access permission.
Exception in thread "main" org.sagebionetworks.client.exceptions.SynapseForbiddenException: Anonymous users have only READ access permission.
        at org.sagebionetworks.client.ClientUtils.throwException(ClientUtils.java:71)
        at org.sagebionetworks.client.ClientUtils.throwException(ClientUtils.java:159)
        at org.sagebionetworks.client.ClientUtils.convertResponseBodyToJSONAndThrowException(ClientUtils.java:108)
        at org.sagebionetworks.client.BaseClientImpl.getJson(BaseClientImpl.java:417)
        at org.sagebionetworks.client.BaseClientImpl.getJSONEntity(BaseClientImpl.java:650)
        at org.sagebionetworks.client.SynapseClientImpl.getEntityFileHandlesForCurrentVersion(SynapseClientImpl.java:1997)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
        at com.sun.proxy.$Proxy5.getEntityFileHandlesForCurrentVersion(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:46)
        at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:43)
        at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:64)
        at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:43)
        at com.sun.proxy.$Proxy5.getEntityFileHandlesForCurrentVersion(Unknown Source)
        at org.sagebionetworks.WorkflowOrchestrator.getWorkflowURLAndEntrypoint(WorkflowOrchestrator.java:177)
        at org.sagebionetworks.WorkflowOrchestrator.execute(WorkflowOrchestrator.java:215)
        at org.sagebionetworks.WorkflowOrchestrator.main(WorkflowOrchestrator.java:116)
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down signal received.
[Thread-1] INFO org.sagebionetworks.ShutdownHook - Shut down complete.
```

**Comment by thomasyu888** [comment]
Confirmed that this still works: https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/releases/tag/untagged-d69053e643036e9a0668

**Comment by brucehoff** [comment]
Here's the commit to the SynapseWorkflowHook repository: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/5f3cc549abab63571076594e3cf6f0fefcbe9265
