### ISSUE TITLE
Docker daemon not found on docker run

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#9]
```
STDERR: 2018-10-01T19:55:46.575401900Z DEBUG:rdflib:RDFLib Version: 4.2.2
STDERR: 2018-10-01T19:55:46.822124200Z Resolved 'ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl' to 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl'
STDERR: 2018-10-01T19:55:46.822170800Z INFO:cwltool:Resolved 'ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl' to 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/dockerAgent_workflow.cwl'
STDERR: 2018-10-01T19:55:49.504402600Z WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
STDERR: 2018-10-01T19:55:49.504454100Z WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (2095771648).
STDERR: 2018-10-01T19:55:49.507461600Z WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (129787301888).
STDERR: 2018-10-01T19:55:49.544431700Z INFO:toil:Running Toil version 3.17.0-585383ed5c4453b556269818571d3c7419c613b0.
STDERR: 2018-10-01T19:55:49.544601700Z INFO:toil.realtimeLogger:Real-time logging disabled
STDERR: 2018-10-01T19:55:50.488453000Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDOUT: 2018-10-01T19:55:50.488672800Z 2018-10-01 19:55:50,487 - toil.leader - INFO - Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-01T19:55:50.489039000Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ with job batch system ID: 2 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDOUT: 2018-10-01T19:55:50.489130600Z 2018-10-01 19:55:50,488 - toil.leader - INFO - Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ with job batch system ID: 2 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-01T19:55:54.329694500Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd
STDOUT: 2018-10-01T19:55:54.329889700Z 2018-10-01 19:55:54,328 - toil.leader - INFO - Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd
STDERR: 2018-10-01T19:55:55.572106200Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ
STDOUT: 2018-10-01T19:55:55.572198600Z 2018-10-01 19:55:55,571 - toil.leader - INFO - Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ
STDERR: 2018-10-01T19:55:55.573620400Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/validateDocker.cwl' python 6/0/jobtgXwgj with job batch system ID: 3 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDOUT: 2018-10-01T19:55:55.573706200Z 2018-10-01 19:55:55,573 - toil.leader - INFO - Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/validateDocker.cwl' python 6/0/jobtgXwgj with job batch system ID: 3 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-01T19:55:55.581143600Z INFO:toil.leader:Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with job batch system ID: 4 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDOUT: 2018-10-01T19:55:55.581571800Z 2018-10-01 19:55:55,580 - toil.leader - INFO - Issued job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with job batch system ID: 4 and cores: 1, disk: 2.0 G, and memory: 100.0 M
STDERR: 2018-10-01T19:55:57.220026000Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW
STDOUT: 2018-10-01T19:55:57.220320600Z 2018-10-01 19:55:57,219 - toil.leader - INFO - Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW
STDERR: 2018-10-01T19:55:57.221043400Z WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW
STDOUT: 2018-10-01T19:55:57.221250700Z 2018-10-01 19:55:57,220 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW
STDERR: 2018-10-01T19:55:57.221498300Z WARNING:toil.leader:D/t/jobKbiDqW    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
STDOUT: 2018-10-01T19:55:57.221596000Z 2018-10-01 19:55:57,221 - toil.leader - WARNING - D/t/jobKbiDqW    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
STDERR: 2018-10-01T19:55:57.221829900Z WARNING:toil.leader:D/t/jobKbiDqW    INFO:toil:Running Toil version 3.17.0-585383ed5c4453b556269818571d3c7419c613b0.
STDOUT: 2018-10-01T19:55:57.221942100Z 2018-10-01 19:55:57,221 - toil.leader - WARNING - D/t/jobKbiDqW    INFO:toil:Running Toil version 3.17.0-585383ed5c4453b556269818571d3c7419c613b0.
STDERR: 2018-10-01T19:55:57.222150700Z WARNING:toil.leader:D/t/jobKbiDqW    [job runDocker.cwl] /Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/out_tmpdirJ4WMZS$ docker \
STDOUT: 2018-10-01T19:55:57.222282400Z 2018-10-01 19:55:57,221 - toil.leader - WARNING - D/t/jobKbiDqW    [job runDocker.cwl] /Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/out_tmpdirJ4WMZS$ docker \
STDERR: 2018-10-01T19:55:57.222544700Z WARNING:toil.leader:D/t/jobKbiDqW        run \
STDOUT: 2018-10-01T19:55:57.222725800Z 2018-10-01 19:55:57,222 - toil.leader - WARNING - D/t/jobKbiDqW        run \
STDERR: 2018-10-01T19:55:57.222997600Z WARNING:toil.leader:D/t/jobKbiDqW        -i \
STDOUT: 2018-10-01T19:55:57.223010000Z 2018-10-01 19:55:57,222 - toil.leader - WARNING - D/t/jobKbiDqW        -i \
STDERR: 2018-10-01T19:55:57.223223200Z WARNING:toil.leader:D/t/jobKbiDqW        --volume=/tmp:/input:ro \
STDOUT: 2018-10-01T19:55:57.223497000Z 2018-10-01 19:55:57,222 - toil.leader - WARNING - D/t/jobKbiDqW        --volume=/tmp:/input:ro \
STDERR: 2018-10-01T19:55:57.223687100Z WARNING:toil.leader:D/t/jobKbiDqW        --volume=/tmp/out_tmpdirJ4WMZS:/output:rw \
STDOUT: 2018-10-01T19:55:57.223819700Z 2018-10-01 19:55:57,223 - toil.leader - WARNING - D/t/jobKbiDqW        --volume=/tmp/out_tmpdirJ4WMZS:/output:rw \
STDERR: 2018-10-01T19:55:57.224022100Z WARNING:toil.leader:D/t/jobKbiDqW        --memory \
STDOUT: 2018-10-01T19:55:57.224106300Z 2018-10-01 19:55:57,223 - toil.leader - WARNING - D/t/jobKbiDqW        --memory \
STDERR: 2018-10-01T19:55:57.224374500Z WARNING:toil.leader:D/t/jobKbiDqW        200g \
STDOUT: 2018-10-01T19:55:57.224633200Z 2018-10-01 19:55:57,224 - toil.leader - WARNING - D/t/jobKbiDqW        200g \
STDERR: 2018-10-01T19:55:57.224792100Z WARNING:toil.leader:D/t/jobKbiDqW        --memory-swap \
STDERR: 2018-10-01T19:55:57.225095800Z WARNING:toil.leader:D/t/jobKbiDqW        0m \
STDOUT: 2018-10-01T19:55:57.225193600Z 2018-10-01 19:55:57,224 - toil.leader - WARNING - D/t/jobKbiDqW        --memory-swap \
STDOUT: 2018-10-01T19:55:57.225343300Z 2018-10-01 19:55:57,224 - toil.leader - WARNING - D/t/jobKbiDqW        0m \
STDERR: 2018-10-01T19:55:57.225617700Z WARNING:toil.leader:D/t/jobKbiDqW        --net=none \
STDERR: 2018-10-01T19:55:57.225659900Z WARNING:toil.leader:D/t/jobKbiDqW        --name=9681550 \
STDOUT: 2018-10-01T19:55:57.225665900Z 2018-10-01 19:55:57,225 - toil.leader - WARNING - D/t/jobKbiDqW        --net=none \
STDOUT: 2018-10-01T19:55:57.225953700Z 2018-10-01 19:55:57,225 - toil.leader - WARNING - D/t/jobKbiDqW        --name=9681550 \
STDOUT: 2018-10-01T19:55:57.226139400Z 2018-10-01 19:55:57,225 - toil.leader - WARNING - D/t/jobKbiDqW        'docker.synapse.org/syn4990358/testwf@sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c'
STDERR: 2018-10-01T19:55:57.226193600Z WARNING:toil.leader:D/t/jobKbiDqW        'docker.synapse.org/syn4990358/testwf@sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c'
STDERR: 2018-10-01T19:55:57.226443600Z WARNING:toil.leader:D/t/jobKbiDqW    INFO:cwltool:[job runDocker.cwl] /Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/out_tmpdirJ4WMZS$ docker \
STDOUT: 2018-10-01T19:55:57.226530900Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW    INFO:cwltool:[job runDocker.cwl] /Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/out_tmpdirJ4WMZS$ docker \
STDOUT: 2018-10-01T19:55:57.227872200Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW        run \
STDOUT: 2018-10-01T19:55:57.227895700Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW        -i \
STDOUT: 2018-10-01T19:55:57.227907000Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW        --volume=/tmp:/input:ro \
STDOUT: 2018-10-01T19:55:57.227927200Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW        --volume=/tmp/out_tmpdirJ4WMZS:/output:rw \
STDOUT: 2018-10-01T19:55:57.227943000Z 2018-10-01 19:55:57,226 - toil.leader - WARNING - D/t/jobKbiDqW        --memory \
STDOUT: 2018-10-01T19:55:57.227959500Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        200g \
STDOUT: 2018-10-01T19:55:57.227989300Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        --memory-swap \
STDOUT: 2018-10-01T19:55:57.228006700Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        0m \
STDOUT: 2018-10-01T19:55:57.228037500Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        --net=none \
STDOUT: 2018-10-01T19:55:57.228053900Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        --name=9681550 \
STDOUT: 2018-10-01T19:55:57.228070300Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW        'docker.synapse.org/syn4990358/testwf@sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c'
STDOUT: 2018-10-01T19:55:57.228086300Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW    docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
STDOUT: 2018-10-01T19:55:57.228101900Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW    See 'docker run --help'.
STDOUT: 2018-10-01T19:55:57.228117100Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW    [job runDocker.cwl] Job error:
STDERR: 2018-10-01T19:55:57.227970000Z WARNING:toil.leader:D/t/jobKbiDqW        run \
STDERR: 2018-10-01T19:55:57.228146300Z WARNING:toil.leader:D/t/jobKbiDqW        -i \
STDERR: 2018-10-01T19:55:57.228162100Z WARNING:toil.leader:D/t/jobKbiDqW        --volume=/tmp:/input:ro \
STDERR: 2018-10-01T19:55:57.228179700Z WARNING:toil.leader:D/t/jobKbiDqW        --volume=/tmp/out_tmpdirJ4WMZS:/output:rw \
STDERR: 2018-10-01T19:55:57.228195400Z WARNING:toil.leader:D/t/jobKbiDqW        --memory \
STDERR: 2018-10-01T19:55:57.228210600Z WARNING:toil.leader:D/t/jobKbiDqW        200g \
STDERR: 2018-10-01T19:55:57.228225800Z WARNING:toil.leader:D/t/jobKbiDqW        --memory-swap \
STDERR: 2018-10-01T19:55:57.228240900Z WARNING:toil.leader:D/t/jobKbiDqW        0m \
STDERR: 2018-10-01T19:55:57.228255800Z WARNING:toil.leader:D/t/jobKbiDqW        --net=none \
STDERR: 2018-10-01T19:55:57.228270900Z WARNING:toil.leader:D/t/jobKbiDqW        --name=9681550 \
STDERR: 2018-10-01T19:55:57.228286000Z WARNING:toil.leader:D/t/jobKbiDqW        'docker.synapse.org/syn4990358/testwf@sha256:9f09e064ba819cfe811bd19b19ff37dd83fa41d0f53926a70bd8f210b3d3371c'
STDERR: 2018-10-01T19:55:57.228301400Z WARNING:toil.leader:D/t/jobKbiDqW    docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
STDERR: 2018-10-01T19:55:57.228317200Z WARNING:toil.leader:D/t/jobKbiDqW    See 'docker run --help'.
STDERR: 2018-10-01T19:55:57.228332000Z WARNING:toil.leader:D/t/jobKbiDqW    [job runDocker.cwl] Job error:
STDERR: 2018-10-01T19:55:57.228517700Z WARNING:toil.leader:D/t/jobKbiDqW    Error collecting output for parameter 'predictions':
STDERR: 2018-10-01T19:55:57.228537300Z WARNING:toil.leader:D/t/jobKbiDqW    :1:1: Did not find output file with glob pattern: '['listOfFiles.csv']'
STDOUT: 2018-10-01T19:55:57.228537300Z 2018-10-01 19:55:57,227 - toil.leader - WARNING - D/t/jobKbiDqW    Error collecting output for parameter 'predictions':
STDOUT: 2018-10-01T19:55:57.228575600Z 2018-10-01 19:55:57,228 - toil.leader - WARNING - D/t/jobKbiDqW    :1:1: Did not find output file with glob pattern: '['listOfFiles.csv']'
STDOUT: 2018-10-01T19:55:57.228590000Z 2018-10-01 19:55:57,228 - toil.leader - WARNING - D/t/jobKbiDqW    ERROR:cwltool:[job runDocker.cwl] Job error:
STDERR: 2018-10-01T19:55:57.228550300Z WARNING:toil.leader:D/t/jobKbiDqW    ERROR:cwltool:[job runDocker.cwl] Job error:
STDERR: 2018-10-01T19:55:57.228643600Z WARNING:toil.leader:D/t/jobKbiDqW    Error collecting output for parameter 'predictions':
STDERR: 2018-10-01T19:55:57.228812000Z WARNING:toil.leader:D/t/jobKbiDqW    :1:1: Did not find output file with glob pattern: '['listOfFiles.csv']'
STDOUT: 2018-10-01T19:55:57.228854800Z 2018-10-01 19:55:57,228 - toil.leader - WARNING - D/t/jobKbiDqW    Error collecting output for parameter 'predictions':
STDOUT: 2018-10-01T19:55:57.229075800Z 2018-10-01 19:55:57,228 - toil.leader - WARNING - D/t/jobKbiDqW    :1:1: Did not find output file with glob pattern: '['listOfFiles.csv']'
STDERR: 2018-10-01T19:55:57.229374300Z WARNING:toil.leader:D/t/jobKbiDqW    [job runDocker.cwl] completed permanentFail
STDOUT: 2018-10-01T19:55:57.229540300Z 2018-10-01 19:55:57,228 - toil.leader - WARNING - D/t/jobKbiDqW    [job runDocker.cwl] completed permanentFail
STDOUT: 2018-10-01T19:55:57.229851700Z 2018-10-01 19:55:57,229 - toil.leader - WARNING - D/t/jobKbiDqW    WARNING:cwltool:[job runDocker.cwl] completed permanentFail
STDERR: 2018-10-01T19:55:57.229876100Z WARNING:toil.leader:D/t/jobKbiDqW    WARNING:cwltool:[job runDocker.cwl] completed permanentFail
STDERR: 2018-10-01T19:55:57.230185300Z WARNING:toil.leader:D/t/jobKbiDqW    Traceback (most recent call last):
STDERR: 2018-10-01T19:55:57.230439300Z WARNING:toil.leader:D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
STDOUT: 2018-10-01T19:55:57.230460600Z 2018-10-01 19:55:57,229 - toil.leader - WARNING - D/t/jobKbiDqW    Traceback (most recent call last):
STDOUT: 2018-10-01T19:55:57.230766900Z 2018-10-01 19:55:57,230 - toil.leader - WARNING - D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
STDERR: 2018-10-01T19:55:57.230921200Z WARNING:toil.leader:D/t/jobKbiDqW        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
STDOUT: 2018-10-01T19:55:57.231126600Z 2018-10-01 19:55:57,230 - toil.leader - WARNING - D/t/jobKbiDqW        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
STDERR: 2018-10-01T19:55:57.231266100Z WARNING:toil.leader:D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1350, in _runner
STDOUT: 2018-10-01T19:55:57.231402700Z 2018-10-01 19:55:57,231 - toil.leader - WARNING - D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1350, in _runner
STDERR: 2018-10-01T19:55:57.231603700Z WARNING:toil.leader:D/t/jobKbiDqW        returnValues = self._run(jobGraph, fileStore)
STDERR: 2018-10-01T19:55:57.231776400Z WARNING:toil.leader:D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1295, in _run
STDOUT: 2018-10-01T19:55:57.231794800Z 2018-10-01 19:55:57,231 - toil.leader - WARNING - D/t/jobKbiDqW        returnValues = self._run(jobGraph, fileStore)
STDOUT: 2018-10-01T19:55:57.231830200Z 2018-10-01 19:55:57,231 - toil.leader - WARNING - D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1295, in _run
STDERR: 2018-10-01T19:55:57.232014100Z WARNING:toil.leader:D/t/jobKbiDqW        return self.run(fileStore)
STDOUT: 2018-10-01T19:55:57.232036400Z 2018-10-01 19:55:57,231 - toil.leader - WARNING - D/t/jobKbiDqW        return self.run(fileStore)
STDERR: 2018-10-01T19:55:57.232274700Z WARNING:toil.leader:D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 486, in run
STDOUT: 2018-10-01T19:55:57.232411900Z 2018-10-01 19:55:57,232 - toil.leader - WARNING - D/t/jobKbiDqW      File "/usr/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 486, in run
STDERR: 2018-10-01T19:55:57.232644500Z WARNING:toil.leader:D/t/jobKbiDqW        raise cwltool.errors.WorkflowException(status)
STDOUT: 2018-10-01T19:55:57.232729400Z 2018-10-01 19:55:57,232 - toil.leader - WARNING - D/t/jobKbiDqW        raise cwltool.errors.WorkflowException(status)
STDERR: 2018-10-01T19:55:57.232929900Z WARNING:toil.leader:D/t/jobKbiDqW    WorkflowException: permanentFail
STDOUT: 2018-10-01T19:55:57.233125600Z 2018-10-01 19:55:57,232 - toil.leader - WARNING - D/t/jobKbiDqW    WorkflowException: permanentFail
STDOUT: 2018-10-01T19:55:57.233281600Z 2018-10-01 19:55:57,233 - toil.leader - WARNING - D/t/jobKbiDqW    ERROR:toil.worker:Exiting the worker because of a failed job on host 1444fd9b848b
STDERR: 2018-10-01T19:55:57.233294200Z WARNING:toil.leader:D/t/jobKbiDqW    ERROR:toil.worker:Exiting the worker because of a failed job on host 1444fd9b848b
STDOUT: 2018-10-01T19:55:57.233583900Z 2018-10-01 19:55:57,233 - toil.leader - WARNING - D/t/jobKbiDqW    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with ID D/t/jobKbiDqW to 0
STDERR: 2018-10-01T19:55:57.233612800Z WARNING:toil.leader:D/t/jobKbiDqW    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with ID D/t/jobKbiDqW to 0
STDERR: 2018-10-01T19:55:57.234639600Z WARNING:toil.leader:Job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with ID D/t/jobKbiDqW is completely failed
STDOUT: 2018-10-01T19:55:57.234811100Z 2018-10-01 19:55:57,234 - toil.leader - WARNING - Job 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW with ID D/t/jobKbiDqW is completely failed
STDERR: 2018-10-01T19:56:00.943299200Z INFO:toil.leader:Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/validateDocker.cwl' python 6/0/jobtgXwgj
STDOUT: 2018-10-01T19:56:00.943702400Z 2018-10-01 19:56:00,943 - toil.leader - INFO - Job ended successfully: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/validateDocker.cwl' python 6/0/jobtgXwgj
STDERR: 2018-10-01T19:56:05.594089400Z INFO:toil.leader:Finished toil run with 4 failed jobs.
STDERR: 2018-10-01T19:56:05.594174400Z INFO:toil.leader:Failed jobs at end of the run: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW 'CWLWorkflow' C/e/jobbg7zBw 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ
STDOUT: 2018-10-01T19:56:05.594174400Z 2018-10-01 19:56:05,590 - toil.leader - INFO - Finished toil run with 4 failed jobs.
STDOUT: 2018-10-01T19:56:05.594262400Z 2018-10-01 19:56:05,591 - toil.leader - INFO - Failed jobs at end of the run: 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getDockerConfig.cwl' python h/8/job9PmAZd 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/runDocker.cwl' docker D/t/jobKbiDqW 'CWLWorkflow' C/e/jobbg7zBw 'file:///Users/ThomasY/sandbox/5b6e71b5-eaef-4227-b4e8-6271f9b26f17/ChallengeWorkflowTemplates-master/getSubmissionDocker.cwl' python u/J/jobgZ93uQ
STDERR: 2018-10-01T19:56:05.606271400Z Traceback (most recent call last):
STDERR: 2018-10-01T19:56:05.606310400Z   File "/usr/local/bin/toil-cwl-runner", line 11, in <module>
STDERR: 2018-10-01T19:56:05.606356500Z     sys.exit(main())
STDERR: 2018-10-01T19:56:05.606375500Z   File "/usr/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1071, in main
STDERR: 2018-10-01T19:56:05.606386800Z     outobj = toil.start(wf1)
STDERR: 2018-10-01T19:56:05.606396000Z   File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 783, in start
STDERR: 2018-10-01T19:56:05.608900200Z     return self._runMainLoop(rootJobGraph)
STDERR: 2018-10-01T19:56:05.608966100Z   File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 1057, in _runMainLoop
STDERR: 2018-10-01T19:56:05.608991300Z     jobCache=self._jobCache).run()
STDERR: 2018-10-01T19:56:05.609009000Z   File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 242, in run
STDERR: 2018-10-01T19:56:05.615312100Z     raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
STDERR: 2018-10-01T19:56:05.615359100Z toil.leader.FailedJobsException
```

**Comment by thomasyu888** [comment]
https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates - dockerAgent_workflow.cwl

**Comment by brucehoff** [comment]
Excellent, you are pushing the bounds of what can be done with this code.  I had not yet worked through running workflows which themselves run containers.  Just as we pass daemon access to the workflow hook (which is running in a container) we must provide daemon access to the Toil container.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/47c04fee0d9a3b3c4dd4d7aab3b62fb017208de2
